serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: {? {cert-manager-iam-role-arn: ''} : ''}

installCRDs: true

# the securityContext is required, so the pod can access files required to assume the IAM role
securityContext:
  enabled: true
  fsGroup: 1001
