apiVersion: cert-manager.io/v1beta1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: {? {your-email: ''} : ''}
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        route53:
          region: {? {your-aws-region: ''} : ''}
          hostedZoneID: {? {your-hosted-zone-id: ''} : ''}
